### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by Frotty** [maiconpinto/jekyll-theme-prettydocs#2]
Hi, I was able to get the home page working, but not a documentation page with sidebar.
Is this already working correctly?

**Comment by maiconpinto** [comment]
Sorry for long time no answer. I'll to do a documentation better, and refactor the theme.

**Comment by Frotty** [comment]
Hey, thanks for the reply.
Thanksfully @guillermocalvo already did all the work here: https://github.com/xriley/PrettyDocs-Theme/pull/5

Which I am using now :)
